### ISSUE TITLE
Critical bug

### ISSUE THREAD

**Issue by Fsoky** [hexvel/code-editor#1]
тут место } надо | :))))
![image](https://github.com/hexvel/code-editor/assets/61309653/419025f0-c8c0-43b9-a87d-46f94b241888)

**Comment by hexvel** [comment]
> тут место } надо | :)))) ![image](https://private-user-images.githubusercontent.com/61309653/317291022-419025f0-c8c0-43b9-a87d-46f94b241888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDc0MjEsIm5iZiI6MTcxMTU0NzEyMSwicGF0aCI6Ii82MTMwOTY1My8zMTcyOTEwMjItNDE5MDI1ZjAtYzhjMC00M2I5LWE4N2QtNDZmOTRiMjQxODg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEzNDUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ODAzMGVkNDkyZmYxOGVmYWY4NjU2YmJiMTY0ZDgxZGMzZGJmM2Y2YTRmYmZlNDFlOTYxNWIzNDQ5Mzk1MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fHImnRIcBVkCrAD3Jk-Z80mIU4tUN31_RuHRPU4pKDk)

спасибо!, исправил
